"""add Note, Tag

Revision ID: 455f37b74619
Revises: d4919297e2b7
Create Date: 2026-06-07 14:51:28.918313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '455f37b74619'
down_revision: Union[str, Sequence[str], None] = 'd4919297e2b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Note_Tag', sa.Column('note_id', sa.String(length=36), nullable=True))
    op.drop_constraint(op.f('Note_Tag_ibfk_2'), 'Note_Tag', type_='foreignkey')
    op.create_foreign_key(None, 'Note_Tag', 'Note', ['note_id'], ['id'])
    op.drop_column('Note_Tag', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Note_Tag', sa.Column('user_id', mysql.VARCHAR(length=36), nullable=True))
    op.drop_constraint(None, 'Note_Tag', type_='foreignkey')
    op.create_foreign_key(op.f('Note_Tag_ibfk_2'), 'Note_Tag', 'Note', ['user_id'], ['id'])
    op.drop_column('Note_Tag', 'note_id')
    # ### end Alembic commands ###
